### PR TITLE
quick fix™: clean command triggers

### PR DESCRIPTION
**Pull request by brxxn**
I can't test this rn and made it in github editor (probably should have cloned it lol) but it looks right. Uses `await Utils.clean(trigger)` to clean command triggers and content.

### CODE REVIEW

**Comment by Kitty-Therapist** [comment]
Tested this on my test bot since brxxn was not able to. This is how it's looking at the moment: https://i.imgur.com/1XlhKwN.png Just needs a little bit of clean-up, but it appears to be fixed now and nothing exploded.

**Comment by brxxn** [comment]
@Kitty-Therapist do i need to make changes?

**Comment by Kitty-Therapist** [comment]
@brxxn nah, you're fine as far that I can tell. If AE wants to make a change or request it, he will.

**Comment by AEnterprise** [comment]
while yes the escape mentions would be nice to use, i'm just gona deploy this as a quick fix until i fix it properly due to how much this can be abused

**Pull request merged**
