### PR TITLE
Bug fixes for custom command channel list and DM on unmute 

### PR DESCRIPTION
**Pull request by Spudds**
**What does this PR add/fix/improve/...**
Stops DM on unmute failing and fixes another mix up with the order of the custom command channel list commands (add and remove).

**Migration**
N/A

**Dependencies**
N/A

### CODE REVIEW

**Comment by Spudds** [comment]
I was also going to change [this](https://github.com/Spudds/GearBot/blob/live/GearBot/Cogs/ServerAdmin.py#L1300) so there'd be a list of channels too, but I didn't know if that pass was put there for any particular reason. If not I'd be more than happy to add it.

**Comment by AEnterprise** [comment]
@Spudds feel free to add that channel list

**Review by AEnterprise — APPROVED** [review]
looks good on first sight, will leave this pending however for a bit while i'm preparing the gearbot dockerization and server migration

**Comment by Spudds** [comment]
Alrighty, thanks.

**Pull request merged**
